
SHELL       := /usr/bin/env bash

SRC_DIR     := ./src
INC_DIR     := ./inc
OBJ_DIR     := ./obj
BIN_DIR     := ./bin
LIB_DIR     := ../../../../libctboard
COMMON_DIR  := ../../../../common

AS_SRC      := assembly_io.s

C_DEF       := PLATFORM_M0
C_INC       :=
C_SRC       := main.c

include     $(COMMON_DIR)/root.mk
